<a href="https://colab.research.google.com/github/d-hackmt/Fundamentalss-of-Deep-Learning/blob/main/Loss_func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loss function is used for neural network training

In [ ]:
import numpy as np

In [ ]:
y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])


Mean ABsolute error is nothing but your absolute difference between true value and predicted value and the average of that

In [ ]:
def mae(y_true , y_pred):
  total_error = 0
  # how do you run for loop parallely on 2 array,zip will give one value of oth these array in each iteration

  for yt ,yp in zip(y_true , y_pred):
    #print(yt , yp)
    total_error += abs(yt-yp)
  print("Total errror =" , total_error)
  mae = total_error / len(y_true)
  print("Mae =" , mae)
  return mae


In [ ]:
mae(y_true , y_pred)

Total errror = 2.5
Mae = 0.5


0.5

In [ ]:
y_pred - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [ ]:
abs = np.abs (y_pred - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [ ]:
 # all above function in one line 
 #power of numpy
 
meanabs=  np.mean(np.abs (y_pred - y_true))
meanabs

0.5

Implement Log Loss or Binary Cross Entropy

note here everytime i have wrote eplison is EPSILON

In [ ]:
np.log([0])

<ipython-input-39-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [ ]:
# log 0 is undefined
# to deal with this we have to do the following

# we have to replace the value of 0 by closest number to 0
# eplison

eplison = 1e-15   # (e raise to -15 hai wo)
np.log([1e-15])


array([-34.53877639])

In [ ]:
y_pred

array([1, 1, 0, 0, 1])

In [ ]:
y_pred_new = [max(i , eplison )for i in y_pred]        #list comprehension   each i is each value in ypred and we want an max between i and eplison
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [ ]:
1-eplison

0.999999999999999

In [ ]:
y_pred_new = [min(i,1-eplison) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 0.0, 0.0, 0.999999999999999]

In [ ]:
y_pred_new = np.array(y_pred_new)

In [ ]:
np.log(y_pred_new)

<ipython-input-45-a3436cf2b2dd>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_pred_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])

In [ ]:
-np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

<ipython-input-46-7b1793610236>:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))
<ipython-input-46-7b1793610236>:1: RuntimeWarning: invalid value encountered in multiply
  -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))


nan

In [ ]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,eplison) for i in y_predicted]
    y_predicted_new = [min(i,1-eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
log_loss(y_true , y_pred)

17.2696280766844

Loss function practice

Implement Mean Squared Error Function In Python

You need to implement mean squared error function first without using numpy and then using numpy

Without using numpy

In [ ]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [ ]:
def mse(y_true , y_predicted):
  total_error = 0
  for yt, yp in zip(y_true , y_predicted):
    total_error += (yt - yp)**2
  print("Total squared error",total_error)
  mse = total_error / len(y_true)
  print("Mean absolute Error ", mse)
  return mse

In [ ]:
mse(y_true , y_predicted)

Total squared error 1.83
Mean absolute Error  0.366


0.366

WIth numpy

In [ ]:
np.mean(np.square(y_true - y_predicted))

0.366