<a href="https://colab.research.google.com/github/d-hackmt/Fundamentalss-of-Deep-Learning/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])
revenue,expenses

(array([[180, 200, 220],
        [ 24,  36,  40],
        [ 12,  18,  20]]), array([[ 80,  90, 100],
        [ 10,  16,  20],
        [  8,  10,  10]]))

In [ ]:
revenue.shape , expenses.shape

((3, 3), (3, 3))

In [ ]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [ ]:
price_per_unit = np.array([1000 , 400 , 1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
price_per_unit , units

(array([1000,  400, 1200]), array([[30, 40, 50],
        [ 5, 10, 15],
        [ 2,  5,  7]]))

In [ ]:
sales = price_per_unit * units   
sales
# Now here we know its wrong and we cant multiply like this in matrices but here 
# this what happened was broadcasting 

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

is a shape of 2 matrix is not same it will try to expand it 
so it multiplied it as if

price_per_unit = np.array([[1000 , 400 , 1200] ,[1000 , 400 , 1200],[1000 , 400 , 1200]] ) 

In [ ]:
#so now we do it right using dot product

total_sales = np.dot(price_per_unit , units)

total_sales

array([34400, 50000, 64400])

## LETS PRACTICE

A problem to convert all us dollars into inr

 Convert USD revenues to INR

In [ ]:
import numpy as np

In [ ]:
revenues_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenues_inr = 75*revenues_usd
revenues_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

Calculate total flowers sale every month for divine flowers shop

In [ ]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [ ]:
sales = np.dot(price_per_unit ,units_sold )

In [ ]:
sales

array([1900, 2640, 1430])